#!/bin/bash

#########################################################
# Function :check application shell                     #
# Platform :All Linux Based Platform                    #
# Version  :1.0                                         #
# Date     :2024-06-25                                  #
# Author   :Cookie.Fei                                  #
# Contact  :zhoufei@uniontech.com                       #
# Company  :www.uniontech.com                           #
#########################################################


args="$1"
baselines="$@"

# 定义帮助信息函数
help_command() {
    echo "Usage: $0 [options...]"
    echo
    echo "Options:"
    echo "  -h, --help         display this help message"
    echo "  -l, --list         show baseline version list"
    echo "  -v, --version      display script version"
    echo "  -e, --example      display how to use tool"
    # 添加其他选项的帮助信息
}

if [ "x$args" = "x" ];then
    args="-h"
fi

# 检查参数并执行相应的命令
case $args in
    -h | --help )
        help_command
        exit 0
        ;;
    -v | --version )
        echo "Version 1.0"
        exit 0
        ;;
    -l | --list)
        app-analyze appcheck --list
        exit 0
        ;;
    -e  | --example )
        echo "Usage: "
        echo "  default:"
        echo "    deepin-app-analyze {filepath.deb}"
        echo "    deepin-app-analyze /home/uos/Downloads/apt_1.8.2.11-1+dde_amd64.deb"
        echo "  for one version:"
        echo "    deepin-app-analyze {filepath.deb} {current-version_update-version}"
        echo "    deepin-app-analyze /home/uos/Downloads/apt_1.8.2.11-1+dde_amd64.deb 1050_1051"
        echo "  for multiple versions:"
        echo "    deepin-app-analyze {filepath.deb} {current-version_update-version} {current-version_update-version}"
        echo "    deepin-app-analyze /home/uos/Downloads/apt_1.8.2.11-1+dde_amd64.deb 1050_1051 1051_1052"
        exit 0
        ;;
esac

if [ $# -eq 1 ]; then
    app-analyze appcheck -f $args
else
    app-analyze appcheck -f $args -b "$baselines"
fi