#!/bin/bash

#########################################################
# Function :check application shell                     #
# Platform :All Linux Based Platform                    #
# Version  :1.0                                         #
# Date     :2024-06-25                                  #
# Author   :Cookie.Fei                                  #
# Contact  :zhoufei@uniontech.com                       #
# Company  :www.uniontech.com                           #
#########################################################


args="$1"

# 定义帮助信息函数
help_command() {
    echo "Usage: $0 [options...]"
    echo
    echo "Options:"
    echo "  -h, --help         display this help message"
    echo "  -v, --version      display script version"
    echo "  -e, --example      display how to use tool"
    # 添加其他选项的帮助信息
}

if [ "x$args" = "x" ];then
    args="-h"
fi

# 检查参数并执行相应的命令
case $args in
    -h | --help )
        help_command
        exit 0
        ;;
    -v | --version )
        echo "Version 1.0"
        exit 0
        ;;
    -e  | --example )
        echo "Usage: "
        echo "  deepin-app-analyze {filepath.deb}"
        exit 0
        ;;
esac

app-analyze appcheck -f $args