#!/bin/sh 

#########################################################
# Function :Clean application shell                     #
# Platform :All Linux Based Platform                    #
# Version  :0.0.1                                       #
# Date     :2024-06-24                                  #
# Author   :Cookie.Fei                                  #
# Contact  :zhoufei@uniontech.com                       #
# Company  :www.uniontech.com                           #
#########################################################

